// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mobile.DL.Entity;

namespace Mobile.DL.Migrations
{
    [DbContext(typeof(MobileContext))]
    [Migration("20200205132050_SecondCreate")]
    partial class SecondCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mobile.DL.Enity.MobileItems", b =>
                {
                    b.Property<int>("MobileItemsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MobilePrice")
                        .HasColumnType("int");

                    b.HasKey("MobileItemsId");

                    b.ToTable("MobileItems");
                });

            modelBuilder.Entity("Mobile.DL.Entity.AccessoryItems", b =>
                {
                    b.Property<int>("AccessoryItemsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccessoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccessoryPrice")
                        .HasColumnType("int");

                    b.Property<int>("MobileItemsId")
                        .HasColumnType("int");

                    b.HasKey("AccessoryItemsId");

                    b.HasIndex("MobileItemsId");

                    b.ToTable("AccessoryItems");
                });

            modelBuilder.Entity("Mobile.DL.Entity.AccessoryItems", b =>
                {
                    b.HasOne("Mobile.DL.Enity.MobileItems", null)
                        .WithMany("AccessoryItems")
                        .HasForeignKey("MobileItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
